import express from 'express'

const app = express()

app.get('/characters', function (req, res) {
    res.json([
        {
            name: 'Tim Bisley',
            born: 1974,
            age: 30,
            gender: 'M',
            job: 'Comic Book Artist',
            fact: 'No memory of Christmas 1979/1994',
            actor: 'Simon Pegg',
        },
        {
            name: 'Daisy Steiner',
            born: 1974,
            age: 30,
            gender: 'F',
            job: 'Freelance Writer',
            fact: 'Graduated from Kingston Poly with a third in Humanities',
            actor: 'Jessica Hynes',
        },
        {
            name: 'Marsha Klein',
            born: 1950,
            age: 54,
            gender: 'F',
            job: 'Landlord',
            fact: 'Trained as a top athlete in her youth until meeting her husband',
            actor: 'Julia Deakin',
        },
        {
            name: 'Mike Watt',
            born: 1973,
            age: 31,
            gender: 'M',
            job: 'Territorial Army',
            fact: 'Once stole a tank',
            actor: 'Nick Frost',
        },
        {
            name: 'Brian Topp',
            born: 1971,
            age: 34,
            gender: 'M',
            job: 'Artist',
            fact: "Parents think he's a laywer",
            actor: 'Mark Heap',
        },
        {
            name: 'Twist Morgan',
            born: 1975,
            age: 29,
            gender: 'M',
            job: 'Laundrette',
            fact: 'Has a fashion degree',
            actor: 'Katy Carmichael',
        },
        {
            name: "Tyres O'Flaherty",
            born: 1970,
            age: 35,
            gender: 'M',
            job: 'Bicycle Courier',
            fact: 'Very short attention span',
            actor: 'Michael Smiley',
        },
        {
            name: 'Duane Benzie',
            born: 1971,
            age: 33,
            gender: 'M',
            job: 'Successful Business Man',
            fact: "Boss of Tim's former girlfriend",
            actor: 'Peter Serafinowicz',
        },
        {
            name: 'Bilbo Bagshot',
            age: 45,
            born: 1959,
            gender: 'M',
            job: 'Comic Book Store Manager',
            fact: "Davourite film is 'Hawk the Slayer'",
            actor: 'Bill Bailey',
        },
    ])
})

app.get('/episodes', function (req, res) {
    res.json([
        {
            season: 1,
            episode: 1,
            title: 'Beginnings',
            director: 'Edgar Wright',
            airDate: '24-09-1999',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Daisy Steiner is living in a squat, and Tim Bisley is homeless after breaking up with his girlfriend. The two meet in a cafe and form a friendship as they search for accommodation. When they notice a listing for a flat they like but which is for a 'professional couple' only, they decide to pass themselves off as a long term couple in order to fool Marsha Klein, their prospective landlady.`,
        },
        {
            season: 1,
            episode: 2,
            title: 'Gatherings',
            director: 'Edgar Wright',
            airDate: '01-10-1999',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Daisy plans a housewarming party to avoid doing any work. Guests include her friend Twist Morgan, Marsha, and Brian Topp who lives in the same building. Marsha's daughter Amber throws a separate party upstairs, to which all the guests eventually go.`,
        },
        {
            season: 1,
            episode: 3,
            title: 'Art',
            director: 'Edgar Wright',
            airDate: '08-10-1999',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Tim has spent all night playing Resident Evil 2 and Mike has accidentally travelled to Sheffield. Daisy has a job interview at a classy women's magazine ("Flaps") and Brian has an invitation to a new art show by Vulva (David Walliams), his former partner. At the art show, Tim's hallucinations of zombies cause him to punch Vulva in the face before fleeing. The episode concludes with Daisy's idea for performance art, a parody of Bruce Nauman's work "Clown Torture", which leads Tim to remark that it is obviously harder than it looks.`,
        },
        {
            season: 1,
            episode: 4,
            title: 'Battles',
            director: 'Edgar Wright',
            airDate: '15-10-1999',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `After getting dumped by her boyfriend Richard, Daisy decides to cheer herself up by getting a dog called Colin. Having suffered a fear of dogs since childhood, Tim is not pleased by this. Tim and Mike go paintballing, and encounter Tim's arch-nemesis, Duane Benzie (Peter Serafinowicz), who stole Tim's girlfriend.`,
        },
        {
            season: 1,
            episode: 5,
            title: 'Chaos',
            director: 'Edgar Wright',
            airDate: '22-10-1999',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Daisy is strongly bonding with new dog Colin, much to Tim's displeasure. When Colin disappears while being walked by Tim, Daisy suspects Tim of letting Colin go. But Tim learns that the dog has been abducted by a ruthless, sinister cosmetics testing vivisectionist, and plans a daring rescue attempt.`,
        },
        {
            season: 1,
            episode: 6,
            title: 'Epiphanies',
            director: 'Edgar Wright',
            airDate: '29-10-1999',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Tim's bicycle courier friend Tyres (Michael Smiley) pops round for a cup of tea and decides to take the gang clubbing.`,
        },
        {
            season: 1,
            episode: 7,
            title: 'Ends',
            director: 'Edgar Wright',
            airDate: '05-11-1999',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Tim is ecstatic when his ex-girlfriend Sarah decides she wants him back; Daisy is less so, causing much tension around the flat. Mike has an interview at the Territorial Army to determine whether he should be allowed back in following an incident in which he stole a tank. Following a heated argument, Daisy finally manages to write some articles, and Tim finally realises the right path for him. Brian asks Twist out on a date, and they begin a relationship.`,
        },
        {
            season: 2,
            episode: 1,
            title: 'Back',
            director: 'Edgar Wright',
            airDate: '23-02-2001',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `After receiving an injection of money following the sale of her articles, Daisy returns from her holiday in Asia, but finds it hard to settle back into normal life. Tim, a Star Wars fan, has been deeply upset by the poor quality of The Phantom Menace. Mike has been thrown out of his home after shooting the cat, and is sleeping in Daisy's room. Two sinister black-suited Matrix-like Agents (Kevin Eldon and Mark Gatiss) are hunting for Daisy after her bag was switched by a stranger (John Simm) at the airport.`,
        },
        {
            season: 2,
            episode: 2,
            title: 'Change',
            director: 'Edgar Wright',
            airDate: '02-03-2001',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Following a dispute with a young customer over Jar Jar Binks merchandise and Tim's inability to cope with the Star Wars prequels, Bilbo fires Tim. Daisy is trying to claim benefits at the Job Centre, despite not having signed on to the dole for three months due to her holiday. Brian is horrified to discover that his relationship with Twist is affecting his artistic output. After Amber leaves home, Marsha finds herself a new lodger – Mike.`,
        },
        {
            season: 2,
            episode: 3,
            title: 'Mettle',
            director: 'Edgar Wright',
            airDate: '09-02-2001',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Tim and Mike are in the Robot Wars quarter final, but their robot is sabotaged by a rival (Reece Shearsmith). Meanwhile, after being fired from several jobs, Daisy starts working in a kitchen, where her new boss (Joanna Scanlan) begins to make life difficult for her. Brian comes under stress as he is given little notice of an upcoming exhibition of his work.`,
        },
        {
            season: 2,
            episode: 4,
            title: 'Help',
            director: 'Edgar Wright',
            airDate: '23-02-2001',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `After receiving a call from the mysterious Damien Knox (Clive Russell) of Darkstar Comics (and his seductive assistant Sophie (Lucy Akhurst), Tim employs Tyres to deliver his portfolio of artwork. Tim removes an unflattering caricature of Damien, but Daisy replaces it in an attempt to be helpful. Tim must then retrieve the job-threatening picture before Damien sees it, aided by Mike and Tyres.`,
        },
        {
            season: 2,
            episode: 5,
            title: 'Gone',
            director: 'Edgar Wright',
            airDate: '30-03-2001',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `While spending an evening out in Camden, Tim and Daisy encounter some young hooligans (Lee Ingleby and Adam Deacon) who accuse them of deception. Meanwhile, Tim's nemesis Duane Benzie steals Tim's house keys in an act of revenge for being shot while paintballing.`,
        },
        {
            season: 2,
            episode: 6,
            title: 'Dissolution',
            director: 'Edgar Wright',
            airDate: '06-04-2001',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `At Daisy's birthday party, cracks begin to form between members of the group. Mike is jealous of Sophie taking all of Tim's time, Brian is tired of Twist using him like a fashion accessory, Daisy dislikes Sophie, and Marsha, still believing that Tim and Daisy are a couple, is upset by Tim apparently cheating on Daisy.`,
        },
        {
            season: 2,
            episode: 7,
            title: 'Dissolution',
            director: 'Edgar Wright',
            airDate: '13-04-2001',
            writers: ['Jessica Stevenson', 'Simon Pegg'],
            description: `Marsha, having discovered that Daisy and Tim had lied to her and maintained their deception ever since moving in, is devastated, and decides to sell the house. Daisy is offered a job in Colwyn Bay, while Sophie takes a job in Seattle. Mike concocts a plan to change Marsha and Daisy's minds.`,
        },
    ])
})

app.listen(3000, function () {
    console.log('Server is running on localhost3000')
})
